export const Routes = {
  // pages
  // pages
  Presentation: { path: "/" },
  Dashboards: {
    path1: "/dashboard",
    path2: "/dashboardadmin",
    path3: "/dashboarddoctor",
    path4: "/dashboard2",
  },
  DashboardOverview: {
    path: "/dashboard/overview",
    path2: "/dashboardadmin/overview",
    path3: "/dashboarddoctor/overview",
    path4: "/dashboard2/overview",
  },
  Transactions: { path: "/dashboard/patient_discharge" },
  AdmPatients : { path: "/dashboard/patient_admitted", path2: "/dashboard2/patient_admitted",path3: "/dashboarddoctor/patient_admitted" },
  Settings: { path: "/dashboard/patient_info" },
  FDAdmit: { path: "/dashboard/admit_patient" },
  FDAppoint: { path: "/dashboard/appoint_patient" },
  Patients: {path: "/dashboard/patientlist", path2: "/dashboard2/patientlist"},
  Tests: {path: "/dashboard2/alltests", path2: "/dashboarddoctor/alltests"},
  Doctors: {
    path: "/dashboard/doctor_list",
    path2: "/dashboardadmin/doctor_list",
    path3: "/dashboard2/doctor_list"
  },
  Op_add: { path: "/dashboardadmin/op_add" },
  Op_show: { path: "/dashboardadmin/op_show" },
  Doc_add: { path: "/dashboardadmin/doc_add" },
  Doc_show: { path: "/dashboardadmin/doc_show" },
  Doc_Slot: { path: "/dashboarddoctor/doc_slot" },
  Usr_del: { path: "/dashboardadmin/usr_del" },
  PatientShow: {
    path: "/dashboard2/patients",
    path2: "/dashboarddoctor/patients",
  },
  PatientTest: { path: "/dashboard2/ptest" },
  PatientTreatment: { path: "/dashboard2/ptreatment" },
  PatientDose: { path: "/dashboard2/pdose" },
  PatientStay: { path: "/dashboard2/pstay" },
  AddProcedure: { path: "/dashboard2/procedure" },
  AddMedication: { path: "/dashboard2/medication" },
  AddRoom: { path: "/dashboard2/room" },
  AddBlock: { path: "/dashboard2/block" },
  PQuery: { path: "/dashboarddoctor/pquery" },
  DocMedication: { path: "/dashboarddoctor/docmedication" },
  DocTreatment: { path: "/dashboarddoctor/doctreatment" },
  //Upgrade: { path: "/dashboard/upgrade"},
  BootstrapTables: { path: "/tables/bootstrap-tables" },
  Billing: { path: "/examples/billing" },
  Invoice: { path: "/examples/invoice" },
  Signin: { path: "/sign-in" },
  Signup: { path: "/examples/sign-up" },
  ForgotPassword: { path: "/examples/forgot-password" },
  ResetPassword: { path: "/examples/reset-password" },
  MedicineShow: {
    path: "/dashboards/medicines",
    path2: "/dashboard2/medicines",
  },
  Lock: { path: "/examples/lock" },
  NotFound: { path: "/examples/404" },
  ServerError: { path: "/examples/500" },

  // docs
  AboutUs: { path: "/about-us" },
  ContactUs: { path: "/contact-us" },
  History: { path: "/history" },
  Vision: { path: "/vision" },
  DocsFolderStructure: { path: "/documentation/folder-structure" },
  DocsBuild: { path: "/doctors/doctorslist" },
  DocsChangelog: { path: "/documentation/changelog" },

  // components
  Accordions: { path: "/components/accordions" },
  Alerts: { path: "/components/alerts" },
  Badges: { path: "/components/badges" },
  Widgets: { path: "/widgets" },
  Breadcrumbs: { path: "/components/breadcrumbs" },
  Buttons: { path: "/components/buttons" },
  Forms: { path: "/components/forms" },
  Modals: { path: "/components/modals" },
  Navs: { path: "/components/navs" },
  Navbars: { path: "/components/navbars" },
  Pagination: { path: "/components/pagination" },
  Popovers: { path: "/components/popovers" },
  Progress: { path: "/components/progress" },
  Tables: { path: "/components/tables" },
  Tabs: { path: "/components/tabs" },
  Tooltips: { path: "/components/tooltips" },
  Toasts: { path: "/components/toasts" },
  WidgetsComponent: { path: "/components/widgets" },
};
